const Strings = {
  appName: 'Demo',
  myCart: 'My Cart',
  itemList: 'Item List',
  noItemsAdded: 'No items added',
  addItem: 'ADD  ITEM',
  addMoreItem: 'ADD MORE ITEM',
  update: 'UPDATE',
  edit: 'EDIT ITEM',
  remove: 'REMOVE',
  description: 'Description',
  partName: 'Part Name',
  vehicleMake: 'Vehicle Make',
  vehicleModel: 'Vehicle Model',
  vehicleYear: 'Vehicle Year',
  partType: 'Part Type',
  item:'Item',
  paid:'PAID',
  pricingDetails: 'Pricing Details',
  price: 'Price',
  totalAmount: 'Total Amount',
  items: 'items',
  // item: 'item',
  postingRequirement: 'For posting Requirement You Need to Pay',
  currency: 'SAR',
};

export default Strings;
